### PR TITLE
neptune integration

### PR DESCRIPTION
**Pull request by kamil-kaczmarek**
neptune integration for livelossplot :fireworks:

1. added two kinds of target: matplotlib (default) and neptune
2. if neptune send data from logs to neptune channels, do nor create matplotlbib charts
3. added minimal example as .py and .ipynb

### CODE REVIEW

**Comment by stared** [comment]
@kamil-kaczmarek Looks great, thank you a lot! 

I will add it to README as well.

**Comment by stared** [comment]
@kamil-kaczmarek  One thing I did in a trigger-happy way - it looks like it imports `neptune` even one does not use that. In that case I need to fix that.

**Comment by kamil-kaczmarek** [comment]
@stared thank you!

Regarding trigger-happiness -> I can rewrite `neptune_integration.py` and use try/catch, to handle users who do not have neptune in installed.

**Comment by stared** [comment]
@kamil-kaczmarek I updated it my way. 
(I wanted to avoid `try/except`, as I did for other libraries.)

**Pull request merged**
