### PR TITLE
feat(github) issue templates

### PR DESCRIPTION
**Pull request by stared**
Directly stolen from https://github.com/pytorch/ignite (thx @vfdev-5!).

### CODE REVIEW

**Comment by vfdev-5** [comment]
@stared didn't know about your package. Looks cool ! Just saw the example with ignite and ask myself if we could not make a more generic matplotlib logger of any variable. We can then put it into contrib with dependency on your package. What do you think ?

**Comment by stared** [comment]
@vfdev-5 Sure, if you used livelossplot inside Ignite, I would be delighted!

Ignite code & example is by @Bartolo1024.

Let me know if you have any questions.

**Comment by vfdev-5** [comment]
@stared, actually, the name `PlotLosses*` does not mean plotting loss values, right ?
Can we make possible logging `lr`, running avg batch loss, maybe other things in addition to metrics what is done in Ignite example ? 

I can open an issue in ignite with a FR to setup `LivelossplotLogger` (similar to other loggers we have) and we can also iterate there, if you guys are interested...

**Comment by Bartolo1024** [comment]
@vfdev-5 It is possible to log every float value in PlotLosses. You have to only specify groups or group patterns if you want to use it with some of the available plugins (for ex. matplotlib plots). 
```
groups = {'acccuracy': ['acc', 'val_acc'], 'log-loss': ['loss', 'val_loss'], 'lr': ['lr']}
plotlosses = PlotLosses(groups=groups)

for i in range(10):
    logs = {
        'acc': 1 - np.random.rand() / (i + 2.),
        'val_acc': 1 - np.random.rand() / (i + 0.5),
        'loss': 1. / (i + 2.),
        'val_loss': 1. / (i + 0.5)
    }
    logs['lr'] = 0.1 / 2 ** (i // 5)
    plotlosses.update(logs)
    plotlosses.send()
    sleep(.1)
```
image
I have opened the FR ([link](https://github.com/pytorch/ignite/issues/1069)) and I am interested in possible contribution.

**Pull request merged**
