### PR TITLE
Add support for other series than just training and validation

### PR DESCRIPTION
**Pull request by sebastienlange**
Hi there!

LiveLossPlot is great!

While using it. I did not see that my classification algorithm (3 classes) was rarely predicting class_1.
So having the possibility to add series would have been useful for me. For example val_class_1_accuracy, val_class2_accuracy, val_class3_accuracy.

And finally I did it. Check examples/minimal.ipynb to understand what I did!

### CODE REVIEW

**Comment by sebastienlange** [comment]
By the way, the code is generic for any serie, including validation (after having removed validation code in draw_plot)
PlotLosses(series_fmt={'validation':'val_{}', 'validation class 1': 'val_class1_{}', 'validation class 2': 'val_class2_{}'})

And with a little effort, it should be generic with training serie as well

**Comment by sebastienlange** [comment]
Now the code is generic. Training and validation included.

**Comment by stared** [comment]
@sebastienlange Makes sense, thanks for contributing! Two things I am not sure about:

* are there any possible backward compatibility issues? 
* does it maintain order (important for color consistency and legend order)?

**Comment by sebastienlange** [comment]
@stared  There was a bug with plot order. It is now fixed with my last commit.
I don't think there are any other backward compatibility issue.

**Pull request merged**
